version: "3.8"
services:
  go-backend:
    container_name: go-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/root/go-clean-architecture
    env_file:
      - ./.env
    command: tail -f /dev/null
  
  db-postgres:
    container_name: db-postgres
    image: postgres:15.4
    ports:
      - 5433:5432
    env_file:
      - ./.env

volumes:
  db-postgres-data:

networks:
  default:
    driver: bridge
    external: true
    name: go-shop
