version: "3.8"
services:
  go-backend:
    container_name: go-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      db-postgres:
        condition: service_healthy

  db-postgres:
    container_name: db-postgres
    image: postgres:15.4
    ports:
      - 5433:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-postgres-data:

networks:
  default:
    driver: bridge
    external: true
    name: go-shop
